// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function get(state, field) {
  if (field) {
    return state[/* age */1];
  } else {
    return state[/* email */0];
  }
}

function set(state, field, value) {
  if (field) {
    return /* record */[
            /* email */state[/* email */0],
            /* age */value
          ];
  } else {
    return /* record */[
            /* email */value,
            /* age */state[/* age */1]
          ];
  }
}

var StateLenses = /* module */[
  /* get */get,
  /* set */set
];

console.log("fakenickels@brazil.gov.br");

console.log(0);

var state = /* record */[
  /* email */"fakenickels@brazil.gov.br",
  /* age */0
];

exports.StateLenses = StateLenses;
exports.state = state;
/*  Not a pure module */
