// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function get(values, field) {
  if (field) {
    return values.age;
  } else {
    return values.email;
  }
}

function set(values, field, value) {
  if (field) {
    return {
            email: values.email,
            age: value
          };
  } else {
    return {
            email: value,
            age: values.age
          };
  }
}

var StateLenses = {
  get: get,
  set: set
};

console.log("fakenickels@brazil.gov.br");

console.log(0);

var state = {
  email: "fakenickels@brazil.gov.br",
  age: 0
};

exports.StateLenses = StateLenses;
exports.state = state;
/*  Not a pure module */
